### ISSUE TITLE
Epic 2: Implement multiple Algs

### ISSUE THREAD

**Issue by OiMickBoi** [OiMickBoi/Algorithm-Visualizer#5]
- [ ] hard code sorting algs
- [ ] Create new figma for the new sections each algorithm category should have a radio button then dropdown and a different way of displaying.
- [ ] hard code Graph algorithms:
- [ ] hard code Other algorithms
