### ISSUE TITLE
Epic 3: ASP.NET Web api

### ISSUE THREAD

**Issue by OiMickBoi** [OiMickBoi/Algorithm-Visualizer#6]
- [ ] Set up the [ASP.NET](http://asp.net/) Core Web API project:
- [ ] Define API endpoints:
- [ ] Implement algorithm logic:
- [ ] Connect the frontend to the API:
